---
- name: Install Nginx
  apt: name=nginx state=latest

- name: Copy nginx configuration (without HTTPS enabled)
  template: src=nginx_app_config dest=/etc/nginx/sites-available/metabase owner=root group=root

- name: Disable default config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Symlink to sites-enabled
  file: src=/etc/nginx/sites-available/metabase dest=/etc/nginx/sites-enabled/metabase owner=root group=root state=link

- name: Copy htpasswd
  template: src=htpasswd dest=/etc/nginx/.htpasswd owner=root group=root
